# Resonite streamed btop config

graph_symbol = "block"
graph_symbol_cpu = "block"
graph_symbol_gpu = "default"
graph_symbol_mem = "default"
graph_symbol_net = "default"
graph_symbol_proc = "default"

shown_boxes = "mem proc cpu net"

show_disks = true
only_physical = false
use_fstab = false
zfs_hide_datasets = false

show_io_stat = true
io_mode = true
io_graph_combined = true

# Games / VR
disks_filter = "/home/troyborg/Resonite/Cache /home/troyborg/Resonite/Data /home"

mem_graphs = true
zfs_arc_cached = true
show_swap = false
swap_disk = false

shown_boxes = "mem proc cpu gpu0 net"

show_gpu_info = "On"
shown_gpus = "nvidia amd intel"
custom_gpu_name0 = "Nvidia RTX 3090"

graph_symbol_gpu = "block"
